.TH lswt 1 2021-03-07

.SH NAME
lswt - list Wayland toplevels

.SH SYNOPSIS
lswt [options...]

.SH DESCRIPTION
lswt will list all toplevels advertised by a Wayland server using the
foreign-toplevel-management-unstable-v1 protocol extension.

.SH OPTIONS
\fB-h\fR, \fB--help\fR
.RS 4
Print help text and exit.
.P
.RE
\fB-a\fR, \fB--all\fR
.RS 4
Show all available information about the toplevels.
.P
.RE
\fB-j\fR, \fB--json\fR
.RS 4
Output data in the JSON format. Implicitly enables \fB-a\fR.
.P
.P
.RE

.SH AUTHOR
Leon Henrik Plickat
.P

