.TH LSWT 1 2021-07-17 "git.sr.ht/~leon_plickat/lswt" "General Commands Manual"
.
.SH NAME
.P
lswt \- list Wayland toplevels
.
.
.SH SYNOPSIS
.SY lswt
.OP \-t
.OP \-\-tsv
.OP \-j
.OP \-\-json
.YS
.
.SY lswt
.OP \-h
.OP \-\-help
.YS
.
.SY lswt
.OP \-v
.OP \-\-version
.YS
.
.
.SH DESCRIPTION
.P
lswt will list all toplevels advertised by a Wayland server using the
\fBforeign-toplevel-management-unstable-v1\fR protocol extension.
.P
By default lswt tries to format the data to be human readable.
If you want to parse the output, consider using one of the available machine
readable output modes.
.P
.RS
.B id: state title app-id
.RE
.P
The \fBid\fR indicates in what order the toplevels have been advertised by the
server.
It is also helpful to identify the same toplevel on multiple outputs.
.P
The \fBstate\fR is a four wide character field, corresponding to the four
possible toplevel states: maximized, minimized, activated and fullscreen.
If one of these states is true for a toplevel, the respective character in the
field is set to the first letter of the state name, otherwise it is \-.
.P
The server must implement the \fBxdg-output-unstable-v1\fR protocol extension
for lswt to fetch the output names.
If the extension is not supported, the object id of the output, which is a
basically a useless integer, is used instead to keep the output consistent.
.P
The machine readable formats additionally expose the object id of the toplevel
handle.
Please note that this can not be used to reliably identify unique toplevels,
because the Wayland protocol allows to recycle object ids.
.
.
.SH OPTIONS
.P
\fB-h\fR, \fB--help\fR
.RS
Print help text and exit.
.RE
.
.P
\fB-v\fR, \fB--version\fR
.RS
Print version and exit.
.RE
.
.P
\fB-t\fR, \fB--tsv\fR
.RS
Output data as tab separated values.
The values are ordered as follows: title, app-id, maximized, minimized,
activated, fullscreen, outputs, object-id.
Title and app-id are quoted.
States are boolean (\(dqtrue\(dq or \(dqfalse\(dq).
The outputs field is a comma separated list of the quoted names of outputs the
toplevel is on or \(dqnone\(dq if the toplevel is not on any output.
.RE
.
.P
\fB-j\fR, \fB--json\fR
.RS
Output data in the JSON format.
.RE
.
.
.SH AUTHOR
.P
.MT leonhenrik.plickat@stud.uni-goettingen.de
Leon Henrik Plickat
.ME
